import Mathlib

open Finset BigOperators

/-! # Ghost engine — exported arithmetic-function identities

    Auto-generated by the Ghost structured invention engine. Each identity below was DISCOVERED
    and PROVED for all n by the engine (multiplicativity reduction + a linear recurrence on prime
    powers, discovered from data). Here Lean's kernel INDEPENDENTLY re-verifies a bounded instance
    (n ≤ 64) by computation via `native_decide` — a check that does not trust the engine at all.
    Build with mathlib: `lake build`. The unbounded ∀n versions are the engine's contribution;
    proving them inside Lean (e.g. `Nat.sum_totient` for Gauss) is a separate, standard exercise. -/

-- Gauss:  ∑_{d ∣ n} φ(d) = n
theorem ghost_gauss_le64 :
    ∀ n ∈ Finset.Icc 1 64, (∑ d ∈ n.divisors, Nat.totient d) = n := by
  native_decide

-- φ * τ = σ :  ∑_{d ∣ n} φ(d) · τ(n/d) = ∑_{d ∣ n} d
theorem ghost_phi_tau_eq_sigma_le64 :
    ∀ n ∈ Finset.Icc 1 64,
      (∑ d ∈ n.divisors, Nat.totient d * (n / d).divisors.card) = (∑ d ∈ n.divisors, d) := by
  native_decide

-- 1 * id² = σ₂ :  ∑_{d ∣ n} (n/d)² = ∑_{d ∣ n} d²
theorem ghost_sigma2_reindex_le64 :
    ∀ n ∈ Finset.Icc 1 64, (∑ d ∈ n.divisors, (n / d) ^ 2) = (∑ d ∈ n.divisors, d ^ 2) := by
  native_decide
